// <auto-generated />
using System;
using EarlyBirdScience.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EarlyBirdScience.Migrations
{
    [DbContext(typeof(EarlyBirdScienceContext))]
    partial class EarlyBirdScienceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EarlyBirdScience.Models.CommentModel", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int?>("DateModelDateId");

                    b.Property<int?>("PostModelPostId");

                    b.Property<bool>("Removed");

                    b.HasKey("CommentId");

                    b.HasIndex("DateModelDateId");

                    b.HasIndex("PostModelPostId");

                    b.ToTable("CommentModel");
                });

            modelBuilder.Entity("EarlyBirdScience.Models.DateModel", b =>
                {
                    b.Property<int>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("DateId");

                    b.ToTable("DateModel");
                });

            modelBuilder.Entity("EarlyBirdScience.Models.PostModel", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CommentsEnabled");

                    b.Property<string>("Content");

                    b.Property<int?>("DateId");

                    b.Property<DateTime>("PublishDate");

                    b.Property<bool>("Published");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(140);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("PostId");

                    b.HasIndex("DateId");

                    b.ToTable("PostModel");
                });

            modelBuilder.Entity("EarlyBirdScience.Models.CommentModel", b =>
                {
                    b.HasOne("EarlyBirdScience.Models.DateModel", "DateModel")
                        .WithMany()
                        .HasForeignKey("DateModelDateId");

                    b.HasOne("EarlyBirdScience.Models.PostModel")
                        .WithMany("Comments")
                        .HasForeignKey("PostModelPostId");
                });

            modelBuilder.Entity("EarlyBirdScience.Models.PostModel", b =>
                {
                    b.HasOne("EarlyBirdScience.Models.DateModel", "Date")
                        .WithMany()
                        .HasForeignKey("DateId");
                });
#pragma warning restore 612, 618
        }
    }
}
